repos:
    # general hooks to verify or beautify code
    - repo: http://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
      - id: check-added-large-files

      - id: trailing-whitespace



      - id: check-yaml



      - id: mixed-line-ending


    # autoformat code with black formatter
    - repo: https://github.com/psf/black
      rev: 20.8b1
      hooks:
        - id: black
          additional_dependencies: [click==8.0.4]
          types: [python]
          args: [-l 120]
